### ISSUE TITLE
transmit complete detection on serial

### ISSUE THREAD

**Issue by nicolas-rabault** [pollen-robotics/stm32f0#42]
The block! macro control if the hardware is ready before sending the data to the serial peripheral, but in some case we need to check if the hardware finish his job before doing something else (for RS485 drivers for example).
We should have something to check it without sending anything.

**Comment by pierre-rouanet** [comment]
Fixed in https://github.com/pollen-robotics/stm32f0/commit/f9380382c743dfb062fd18c895ff852391eaff79
